FROM alpine

# Make and change into app directory
WORKDIR /app

# The binary directory contains the compiled app 
COPY ./binary/ /app/

# Let Docker bind to port 8080
EXPOSE 8080

# Start the Hummingbird service when the image is run, default to listening on 8080 in production environment
# ENTRYPOINT ["./SmallestServer"]
CMD ["./SmallestServer"]