FROM scratch

# Make and change into app directory
WORKDIR /app

# The binary contains the compiled app and swift-backtrace tool (name changed 
# from swift-backtrace-static) moved by the build script.
COPY ./binary/ /app/

# Let Docker bind to port 8080
EXPOSE 8080

# Start the Hummingbird service when the image is run, default to listening on 8080 in production environment
# ENTRYPOINT ["./hello-world"]
# CMD ["--hostname", "0.0.0.0", "--port", "8080"]

ENTRYPOINT ["./SmallestServer"]
CMD [""]
